# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WMantenimientoDePersonas.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FormMantPersonas(object):
    def setupUi(self, FormMantPersonas):
        FormMantPersonas.setObjectName(_fromUtf8("FormMantPersonas"))
        FormMantPersonas.resize(823, 599)
        self.label_4 = QtGui.QLabel(FormMantPersonas)
        self.label_4.setGeometry(QtCore.QRect(300, 20, 281, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(17)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tabWidget = QtGui.QTabWidget(FormMantPersonas)
        self.tabWidget.setGeometry(QtCore.QRect(20, 270, 431, 281))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.BotonModificar_MP = QtGui.QPushButton(self.tab)
        self.BotonModificar_MP.setGeometry(QtCore.QRect(310, 100, 75, 23))
        self.BotonModificar_MP.setObjectName(_fromUtf8("BotonModificar_MP"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 60, 46, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEditNombre_MP = QtGui.QLineEdit(self.tab)
        self.lineEditNombre_MP.setGeometry(QtCore.QRect(90, 100, 113, 20))
        self.lineEditNombre_MP.setObjectName(_fromUtf8("lineEditNombre_MP"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEditID_MP = QtGui.QLineEdit(self.tab)
        self.lineEditID_MP.setGeometry(QtCore.QRect(90, 60, 113, 20))
        self.lineEditID_MP.setObjectName(_fromUtf8("lineEditID_MP"))
        self.BotonBorrar_MP = QtGui.QPushButton(self.tab)
        self.BotonBorrar_MP.setEnabled(True)
        self.BotonBorrar_MP.setGeometry(QtCore.QRect(310, 70, 75, 23))
        self.BotonBorrar_MP.setObjectName(_fromUtf8("BotonBorrar_MP"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 46, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEditApellido_MP = QtGui.QLineEdit(self.tab)
        self.lineEditApellido_MP.setGeometry(QtCore.QRect(90, 140, 113, 20))
        self.lineEditApellido_MP.setObjectName(_fromUtf8("lineEditApellido_MP"))
        self.BotonCrear_MP = QtGui.QPushButton(self.tab)
        self.BotonCrear_MP.setGeometry(QtCore.QRect(310, 130, 75, 23))
        self.BotonCrear_MP.setObjectName(_fromUtf8("BotonCrear_MP"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.label_5 = QtGui.QLabel(FormMantPersonas)
        self.label_5.setGeometry(QtCore.QRect(510, 240, 281, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(17)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.tabWidget_2 = QtGui.QTabWidget(FormMantPersonas)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 70, 781, 111))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.BotonBuscar_MP = QtGui.QPushButton(self.tab_2)
        self.BotonBuscar_MP.setGeometry(QtCore.QRect(490, 30, 75, 23))
        self.BotonBuscar_MP.setObjectName(_fromUtf8("BotonBuscar_MP"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(210, 30, 46, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEditID_MP_2 = QtGui.QLineEdit(self.tab_2)
        self.lineEditID_MP_2.setGeometry(QtCore.QRect(270, 30, 113, 20))
        self.lineEditID_MP_2.setObjectName(_fromUtf8("lineEditID_MP_2"))
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.BotonSalir_MP = QtGui.QPushButton(FormMantPersonas)
        self.BotonSalir_MP.setGeometry(QtCore.QRect(20, 560, 75, 23))
        self.BotonSalir_MP.setObjectName(_fromUtf8("BotonSalir_MP"))
        self.frame_2 = QtGui.QFrame(FormMantPersonas)
        self.frame_2.setGeometry(QtCore.QRect(10, 230, 801, 341))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.tableWidget_MP = QtGui.QTableWidget(self.frame_2)
        self.tableWidget_MP.setGeometry(QtCore.QRect(450, 60, 331, 261))
        self.tableWidget_MP.setObjectName(_fromUtf8("tableWidget_MP"))
        self.tableWidget_MP.setColumnCount(3)
        self.tableWidget_MP.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setHorizontalHeaderItem(2, item)
        self.frame = QtGui.QFrame(FormMantPersonas)
        self.frame.setGeometry(QtCore.QRect(10, 60, 801, 151))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.frame.raise_()
        self.frame_2.raise_()
        self.label_4.raise_()
        self.tabWidget.raise_()
        self.label_5.raise_()
        self.tabWidget_2.raise_()
        self.BotonSalir_MP.raise_()

        self.retranslateUi(FormMantPersonas)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormMantPersonas)

    def retranslateUi(self, FormMantPersonas):
        FormMantPersonas.setWindowTitle(_translate("FormMantPersonas", "Ventana Mantenimiento Personas", None))
        self.label_4.setText(_translate("FormMantPersonas", "MANTENIMIENTO DE PERSONAS", None))
        self.BotonModificar_MP.setText(_translate("FormMantPersonas", "Modificar", None))
        self.label.setText(_translate("FormMantPersonas", "ID", None))
        self.label_2.setText(_translate("FormMantPersonas", "Nombre", None))
        self.BotonBorrar_MP.setText(_translate("FormMantPersonas", "Borrar", None))
        self.label_3.setText(_translate("FormMantPersonas", "Apellido", None))
        self.BotonCrear_MP.setText(_translate("FormMantPersonas", "Crear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("FormMantPersonas", "Mantenimiento", None))
        self.label_5.setText(_translate("FormMantPersonas", "LISTADO DE PERSONAS", None))
        self.BotonBuscar_MP.setText(_translate("FormMantPersonas", "Buscar", None))
        self.label_6.setText(_translate("FormMantPersonas", "ID", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("FormMantPersonas", "Mantenimiento", None))
        self.BotonSalir_MP.setText(_translate("FormMantPersonas", "SALIR", None))
        item = self.tableWidget_MP.horizontalHeaderItem(0)
        item.setText(_translate("FormMantPersonas", "ID", None))
        item = self.tableWidget_MP.horizontalHeaderItem(1)
        item.setText(_translate("FormMantPersonas", "Nombre", None))
        item = self.tableWidget_MP.horizontalHeaderItem(2)
        item.setText(_translate("FormMantPersonas", "Apellido", None))

