# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WPrestamos.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FormPrestamoLibros(object):
    def setupUi(self, FormPrestamoLibros):
        FormPrestamoLibros.setObjectName(_fromUtf8("FormPrestamoLibros"))
        FormPrestamoLibros.resize(831, 645)
        self.tabWidget = QtGui.QTabWidget(FormPrestamoLibros)
        self.tabWidget.setGeometry(QtCore.QRect(20, 70, 791, 301))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.BotonBuscar_MP = QtGui.QPushButton(self.tab)
        self.BotonBuscar_MP.setGeometry(QtCore.QRect(300, 130, 75, 23))
        self.BotonBuscar_MP.setObjectName(_fromUtf8("BotonBuscar_MP"))
        self.BotonModificar_MP = QtGui.QPushButton(self.tab)
        self.BotonModificar_MP.setGeometry(QtCore.QRect(300, 70, 75, 23))
        self.BotonModificar_MP.setObjectName(_fromUtf8("BotonModificar_MP"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 50, 81, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEditNombre_MP = QtGui.QLineEdit(self.tab)
        self.lineEditNombre_MP.setGeometry(QtCore.QRect(125, 90, 113, 20))
        self.lineEditNombre_MP.setObjectName(_fromUtf8("lineEditNombre_MP"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 81, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEditID_MP = QtGui.QLineEdit(self.tab)
        self.lineEditID_MP.setGeometry(QtCore.QRect(125, 50, 113, 20))
        self.lineEditID_MP.setObjectName(_fromUtf8("lineEditID_MP"))
        self.BotonBorrar_MP = QtGui.QPushButton(self.tab)
        self.BotonBorrar_MP.setEnabled(True)
        self.BotonBorrar_MP.setGeometry(QtCore.QRect(300, 40, 75, 23))
        self.BotonBorrar_MP.setObjectName(_fromUtf8("BotonBorrar_MP"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 51, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEditApellido_MP = QtGui.QLineEdit(self.tab)
        self.lineEditApellido_MP.setGeometry(QtCore.QRect(125, 130, 113, 20))
        self.lineEditApellido_MP.setObjectName(_fromUtf8("lineEditApellido_MP"))
        self.BotonCrear_MP = QtGui.QPushButton(self.tab)
        self.BotonCrear_MP.setGeometry(QtCore.QRect(300, 100, 75, 23))
        self.BotonCrear_MP.setObjectName(_fromUtf8("BotonCrear_MP"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(10, 170, 111, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(420, 10, 351, 251))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(40, 70, 71, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_IDPersona_PL = QtGui.QLabel(self.frame_2)
        self.label_IDPersona_PL.setGeometry(QtCore.QRect(140, 60, 181, 31))
        self.label_IDPersona_PL.setText(_fromUtf8(""))
        self.label_IDPersona_PL.setObjectName(_fromUtf8("label_IDPersona_PL"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(40, 120, 50, 12))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_Nombre_PL = QtGui.QLabel(self.frame_2)
        self.label_Nombre_PL.setGeometry(QtCore.QRect(150, 100, 171, 31))
        self.label_Nombre_PL.setText(_fromUtf8(""))
        self.label_Nombre_PL.setObjectName(_fromUtf8("label_Nombre_PL"))
        self.label_Autor_PL = QtGui.QLabel(self.frame_2)
        self.label_Autor_PL.setGeometry(QtCore.QRect(140, 190, 171, 31))
        self.label_Autor_PL.setText(_fromUtf8(""))
        self.label_Autor_PL.setObjectName(_fromUtf8("label_Autor_PL"))
        self.label_13 = QtGui.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(40, 200, 50, 12))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(40, 10, 281, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(17)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(40, 140, 281, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(17)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEditID_MP_2 = QtGui.QLineEdit(self.tab)
        self.lineEditID_MP_2.setGeometry(QtCore.QRect(110, 170, 131, 20))
        self.lineEditID_MP_2.setObjectName(_fromUtf8("lineEditID_MP_2"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.label_5 = QtGui.QLabel(FormPrestamoLibros)
        self.label_5.setGeometry(QtCore.QRect(260, 390, 281, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(17)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_4 = QtGui.QLabel(FormPrestamoLibros)
        self.label_4.setGeometry(QtCore.QRect(240, 30, 281, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(17)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tableWidget_MP = QtGui.QTableWidget(FormPrestamoLibros)
        self.tableWidget_MP.setGeometry(QtCore.QRect(110, 460, 611, 111))
        self.tableWidget_MP.setObjectName(_fromUtf8("tableWidget_MP"))
        self.tableWidget_MP.setColumnCount(6)
        self.tableWidget_MP.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setHorizontalHeaderItem(5, item)
        self.BotonSalir_PL = QtGui.QPushButton(FormPrestamoLibros)
        self.BotonSalir_PL.setEnabled(True)
        self.BotonSalir_PL.setGeometry(QtCore.QRect(30, 610, 75, 23))
        self.BotonSalir_PL.setObjectName(_fromUtf8("BotonSalir_PL"))
        self.frame = QtGui.QFrame(FormPrestamoLibros)
        self.frame.setGeometry(QtCore.QRect(30, 440, 781, 181))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.frame.raise_()
        self.tabWidget.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.tableWidget_MP.raise_()
        self.BotonSalir_PL.raise_()

        self.retranslateUi(FormPrestamoLibros)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormPrestamoLibros)

    def retranslateUi(self, FormPrestamoLibros):
        FormPrestamoLibros.setWindowTitle(_translate("FormPrestamoLibros", "Ventana Prestamos", None))
        self.BotonBuscar_MP.setText(_translate("FormPrestamoLibros", "Buscar", None))
        self.BotonModificar_MP.setText(_translate("FormPrestamoLibros", "Modificar", None))
        self.label.setText(_translate("FormPrestamoLibros", "ID Persona", None))
        self.label_2.setText(_translate("FormPrestamoLibros", "ISBN", None))
        self.BotonBorrar_MP.setText(_translate("FormPrestamoLibros", "Borrar", None))
        self.label_3.setText(_translate("FormPrestamoLibros", "Autor", None))
        self.BotonCrear_MP.setText(_translate("FormPrestamoLibros", "Crear", None))
        self.label_6.setText(_translate("FormPrestamoLibros", "Fecha De Prestamo", None))
        self.label_8.setText(_translate("FormPrestamoLibros", "ID Persona", None))
        self.label_10.setText(_translate("FormPrestamoLibros", "Nombre", None))
        self.label_13.setText(_translate("FormPrestamoLibros", "Autor", None))
        self.label_9.setText(_translate("FormPrestamoLibros", "USUARIO", None))
        self.label_11.setText(_translate("FormPrestamoLibros", "LIBRO", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("FormPrestamoLibros", "Mantenimiento", None))
        self.label_5.setText(_translate("FormPrestamoLibros", "LISTADO DE PRESTAMOS", None))
        self.label_4.setText(_translate("FormPrestamoLibros", "PRESTAMO DE LIBROS", None))
        item = self.tableWidget_MP.horizontalHeaderItem(0)
        item.setText(_translate("FormPrestamoLibros", "ID Persona", None))
        item = self.tableWidget_MP.horizontalHeaderItem(1)
        item.setText(_translate("FormPrestamoLibros", "Nombre", None))
        item = self.tableWidget_MP.horizontalHeaderItem(2)
        item.setText(_translate("FormPrestamoLibros", "Apellido", None))
        item = self.tableWidget_MP.horizontalHeaderItem(3)
        item.setText(_translate("FormPrestamoLibros", "Autor/Libro", None))
        item = self.tableWidget_MP.horizontalHeaderItem(4)
        item.setText(_translate("FormPrestamoLibros", "ISBN", None))
        item = self.tableWidget_MP.horizontalHeaderItem(5)
        item.setText(_translate("FormPrestamoLibros", "Fecha", None))
        self.BotonSalir_PL.setText(_translate("FormPrestamoLibros", "SALIR", None))

