# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WMantenimientoLibros.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FormMantLibros(object):
    def setupUi(self, FormMantLibros):
        FormMantLibros.setObjectName(_fromUtf8("FormMantLibros"))
        FormMantLibros.resize(820, 661)
        self.label_4 = QtGui.QLabel(FormMantLibros)
        self.label_4.setGeometry(QtCore.QRect(280, 10, 281, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(17)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tableWidget_MP = QtGui.QTableWidget(FormMantLibros)
        self.tableWidget_MP.setGeometry(QtCore.QRect(100, 470, 611, 111))
        self.tableWidget_MP.setObjectName(_fromUtf8("tableWidget_MP"))
        self.tableWidget_MP.setColumnCount(6)
        self.tableWidget_MP.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MP.setHorizontalHeaderItem(5, item)
        self.tabWidget = QtGui.QTabWidget(FormMantLibros)
        self.tabWidget.setGeometry(QtCore.QRect(40, 60, 721, 341))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.BotonBuscar_ML = QtGui.QPushButton(self.tab)
        self.BotonBuscar_ML.setGeometry(QtCore.QRect(450, 150, 75, 23))
        self.BotonBuscar_ML.setObjectName(_fromUtf8("BotonBuscar_ML"))
        self.BotonModificar_ML = QtGui.QPushButton(self.tab)
        self.BotonModificar_ML.setGeometry(QtCore.QRect(450, 90, 75, 23))
        self.BotonModificar_ML.setObjectName(_fromUtf8("BotonModificar_ML"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(140, 40, 46, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEditNroP_ML = QtGui.QLineEdit(self.tab)
        self.lineEditNroP_ML.setGeometry(QtCore.QRect(250, 80, 113, 20))
        self.lineEditNroP_ML.setObjectName(_fromUtf8("lineEditNroP_ML"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(140, 80, 81, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEditIISBN_ML = QtGui.QLineEdit(self.tab)
        self.lineEditIISBN_ML.setGeometry(QtCore.QRect(250, 40, 113, 20))
        self.lineEditIISBN_ML.setObjectName(_fromUtf8("lineEditIISBN_ML"))
        self.BotonBorrar_ML = QtGui.QPushButton(self.tab)
        self.BotonBorrar_ML.setEnabled(True)
        self.BotonBorrar_ML.setGeometry(QtCore.QRect(450, 60, 75, 23))
        self.BotonBorrar_ML.setObjectName(_fromUtf8("BotonBorrar_ML"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(140, 120, 46, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEditIdioma_ML = QtGui.QLineEdit(self.tab)
        self.lineEditIdioma_ML.setGeometry(QtCore.QRect(250, 120, 113, 20))
        self.lineEditIdioma_ML.setObjectName(_fromUtf8("lineEditIdioma_ML"))
        self.BotonCrear_ML = QtGui.QPushButton(self.tab)
        self.BotonCrear_ML.setGeometry(QtCore.QRect(450, 120, 75, 23))
        self.BotonCrear_ML.setObjectName(_fromUtf8("BotonCrear_ML"))
        self.lineEditAutor_ML = QtGui.QLineEdit(self.tab)
        self.lineEditAutor_ML.setGeometry(QtCore.QRect(250, 150, 113, 20))
        self.lineEditAutor_ML.setObjectName(_fromUtf8("lineEditAutor_ML"))
        self.lineEditEditorial_ML = QtGui.QLineEdit(self.tab)
        self.lineEditEditorial_ML.setGeometry(QtCore.QRect(250, 190, 113, 20))
        self.lineEditEditorial_ML.setObjectName(_fromUtf8("lineEditEditorial_ML"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(140, 160, 46, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(140, 190, 51, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.comboBoxCategorias_ML = QtGui.QComboBox(self.tab)
        self.comboBoxCategorias_ML.setGeometry(QtCore.QRect(250, 230, 111, 31))
        self.comboBoxCategorias_ML.setObjectName(_fromUtf8("comboBoxCategorias_ML"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(140, 230, 71, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.BotonSalir_ML = QtGui.QPushButton(FormMantLibros)
        self.BotonSalir_ML.setEnabled(True)
        self.BotonSalir_ML.setGeometry(QtCore.QRect(40, 620, 75, 23))
        self.BotonSalir_ML.setObjectName(_fromUtf8("BotonSalir_ML"))
        self.frame = QtGui.QFrame(FormMantLibros)
        self.frame.setGeometry(QtCore.QRect(40, 430, 731, 201))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(250, -10, 281, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(17)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.frame.raise_()
        self.label_4.raise_()
        self.tableWidget_MP.raise_()
        self.tabWidget.raise_()
        self.BotonSalir_ML.raise_()

        self.retranslateUi(FormMantLibros)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormMantLibros)

    def retranslateUi(self, FormMantLibros):
        FormMantLibros.setWindowTitle(_translate("FormMantLibros", "Mantemiento Libros", None))
        self.label_4.setText(_translate("FormMantLibros", "MANTENIMIENTO DE LIBROS", None))
        item = self.tableWidget_MP.horizontalHeaderItem(0)
        item.setText(_translate("FormMantLibros", "ISBN", None))
        item = self.tableWidget_MP.horizontalHeaderItem(1)
        item.setText(_translate("FormMantLibros", "Nro Paginas", None))
        item = self.tableWidget_MP.horizontalHeaderItem(2)
        item.setText(_translate("FormMantLibros", "Idioma", None))
        item = self.tableWidget_MP.horizontalHeaderItem(3)
        item.setText(_translate("FormMantLibros", "Autor", None))
        item = self.tableWidget_MP.horizontalHeaderItem(4)
        item.setText(_translate("FormMantLibros", "Editorial", None))
        item = self.tableWidget_MP.horizontalHeaderItem(5)
        item.setText(_translate("FormMantLibros", "Categoria", None))
        self.BotonBuscar_ML.setText(_translate("FormMantLibros", "Buscar", None))
        self.BotonModificar_ML.setText(_translate("FormMantLibros", "Modificar", None))
        self.label.setText(_translate("FormMantLibros", "ISBN", None))
        self.label_2.setText(_translate("FormMantLibros", "Nro Paginas", None))
        self.BotonBorrar_ML.setText(_translate("FormMantLibros", "Borrar", None))
        self.label_3.setText(_translate("FormMantLibros", "Idioma", None))
        self.BotonCrear_ML.setText(_translate("FormMantLibros", "Crear", None))
        self.label_5.setText(_translate("FormMantLibros", "Autor", None))
        self.label_6.setText(_translate("FormMantLibros", "Editorial", None))
        self.label_7.setText(_translate("FormMantLibros", "Categoria", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("FormMantLibros", "Mantenimiento", None))
        self.BotonSalir_ML.setText(_translate("FormMantLibros", "SALIR", None))
        self.label_8.setText(_translate("FormMantLibros", "LISTA DE LIBROS", None))

